app:
  resource: "@AppBundle/Resources/config/routing.yml"
  prefix: /

user:
  resource: "@UserBundle/Controller/"
  type: annotation
  prefix: /

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
