# app:
#   resource: "@AppBundle/Resources/config/routing.yml"
#   prefix: /
app:
  resource: "@AppBundle/Controller/"
  type: annotation
  prefix: /

user:
  resource: "@UserBundle/Controller/"
  type: annotation
  prefix: /

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
