welcome:
  path: /
  defaults: { _controller: AppBundle:Default:welcome }

user_interface:
  path: /user
  defaults: { _controller: AppBundle:Default:index }

admin_interface:
  path: /admin
  defaults: { _controller: AppBundle:Admin:index }
