welcome:
  path: /
  defaults: { _controller: AppBundle:Default:welcome }

accueil:
  path: /accueil
  defaults: { _controller: AppBundle:Default:index }

admin_interface:
  path: /admin
  defaults: { _controller: AppBundle:Admin:index }
